Update web-neo-rollback.yaml

diff --git a/.github/workflows/web-neo-rollback.yaml b/.github/workflows/web-neo-rollback.yaml
--- a/.github/workflows/web-neo-rollback.yaml
+++ b/.github/workflows/web-neo-rollback.yaml
@@ -36,4 +36,4 @@ jobs:
         run: | 
           WEB_VERSION=`aws s3 ls  ${{ env.AWS_PRD_BACKUP_S3_BUCKETPATH }} | awk '{print $2}' | sed 's/.$//' | grep -w ${{ github.event.inputs.web_tag_version }} `
           echo $WEB_VERSION
-          # [ ${{ github.event.inputs.web_tag_version }} == $WEB_VERSION ] &&  aws s3 sync ${{ env.AWS_PRD_BACKUP_S3_BUCKETPATH }}${{ github.event.inputs.web_tag_version }} ${{ env.AWS_PRD_S3_BUCKETPATH }} --delete || echo "Rollback Failed"
+          [ ${{ github.event.inputs.web_tag_version }} == $WEB_VERSION ] &&  aws s3 sync ${{ env.AWS_PRD_BACKUP_S3_BUCKETPATH }}${{ github.event.inputs.web_tag_version }} ${{ env.AWS_PRD_S3_BUCKETPATH }} --delete || echo "Rollback Failed"
